### ISSUE TITLE
Adjustments for PurpleAir.com visuals

### ISSUE THREAD

**Issue by Docano** [stjohnjohnson/purple-air.py#5]
Hi this is a great foundation you've laid. Good work. A couple minor things I've observed is when the humidity and temp_f data are displayed on purpleair.com's map, it does an adjustment of +4 to the raw json humidity number and also -8 to the raw json temp_f number.

"Humidity, corrected by adding 4% as a general correction to account for heat generated by the WiFi module in a PurpleAir sensor. This will not be accurate for all situations."

"Temperature (°F) A correction of -8°F is applied to the temperature readings in a PurpleAir sensor. This is a general correction and may not be applicable to all situations."

**Comment by stjohnjohnson** [comment]
Oh that's _really_ interesting.  I didn't realize that.

I wonder if I should make the correction part of the code or a flag to pass.  I'm open to either way.

**Comment by stjohnjohnson** [comment]
Eh, I decided to just fix it.  Interestingly enough the PurpleAir website also handles Atmospheric Pressure offset by elevation.  But I felt I didn't need to adjust for that.
